/* Generated By:JavaCC: Do not edit this line. ConfigFileParserConstants.java */
package testdatagenerator.parser;

public interface ConfigFileParserConstants {

  int EOF = 0;
  int COMMA = 5;
  int LBRACE = 6;
  int RBRACE = 7;
  int LPARAN = 8;
  int RPARAN = 9;
  int COLON = 10;
  int QUOTED_STRING = 11;
  int DOUBLE_VAL = 12;
  int VALID_NAME = 13;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\":\"",
    "<QUOTED_STRING>",
    "<DOUBLE_VAL>",
    "<VALID_NAME>",
  };

}
